[package]
name = "test_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor_like_macros = { path = "../procedural_macros" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"